website/categories/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired, Length
from wtforms.validators import  ValidationError
from website.models import  Category


class NewCategoryForm(FlaskForm):
  title=StringField('Title', validators=[DataRequired(),Length(max= 100)] )
  icon_image = FileField(
    "Upload Category icon", validators=[ FileAllowed(["jpg", "png"]) ]
    )
  submit=SubmitField('Add')

  def validate_title(self, title):
    category=Category.query.filter_by(title= title.data).first()
    if category:
      raise ValidationError("Category Title is already exist")
    
  def validate_icon_image(self, icon_image):
        if not icon_image.data:
            raise ValidationError("Please upload an icon for the category")

website/categories/routes.py
from website.models import  Course, Category
from flask import render_template, url_for, flash, redirect
from website.categories.forms import NewCategoryForm
from website import db
from flask_login import login_required
from flask import get_flashed_messages

### methods ###
from website.helper import save_picture
from website.categories.helper import CourseCountInCategory


from flask import Blueprint
categories_bp=Blueprint("categories_bp", __name__)


@categories_bp.route("/dashboard/new_category", methods=["GET","POST"])
@login_required
def new_category():
  new_category_form=NewCategoryForm()

  if new_category_form.validate_on_submit():
     if new_category_form.icon_image.data:
        icon_file=save_picture(new_category_form.icon_image.data,
                               path="static/images/category_pics")
     category=Category(title= new_category_form.title.data,
                      icon=icon_file
                       )
     db.session.add(category)
     db.session.commit()

     flash("Category has been created!", "success")
     return redirect(url_for("categories_bp.new_category"))
  
  flash_messages = get_flashed_messages()
  
  return render_template(
        "new_category.html",
        title="New Category",
        new_category_form=new_category_form,
        active_tab="new_category",
        flash_messages=flash_messages
    )

@categories_bp.route("/category/<string:category_title>")
def category_list(category_title):
    
    category = Category.query.filter_by(title=category_title).first_or_404()
    category_courses=Course.query.filter_by(category_id=category.id)
    categories=Category.query.all()
    return render_template(
        "category.html",
        title=category.title,
        category=category,
        category_courses=category_courses,
        categories=categories,
        courses_count=CourseCountInCategory(category.id)
      )

website/main/routes.py
import sys
from website.models import Course, Category
from flask import flash, redirect, render_template, request, session, url_for
from flask import get_flashed_messages
from website.main.forms import SearchForm, contactForm

### Methods ###
from website.main.helper import send_contact_email


from flask import Blueprint
main= Blueprint("main", __name__)



@main.route("/", methods=["GET", "POST"] )
def home():
  courses=Course.query.limit(6).all()
  categories=Category.query.all()
  flash_messages = get_flashed_messages()
  return render_template("home.html",  
                         courses= courses,
                         categories= categories,
                         flash_messages= flash_messages
                         )

@main.route("/about")
def about():
  return render_template("about.html", title="About Us")



@main.route("/contact", methods=["GET","POST"])
def contact():
  form= contactForm()
  if form.validate_on_submit():
    name= form.name.data
    email= form.email.data
    message= form.message.data
    
    print(f'\n\n\n Form data: {name}, {email}, {message}', file=sys.stderr) ###
    try:
      send_contact_email(name, email, message)
      flash('The request was successfully submitted!', 'success')
    except Exception as e:
      flash(f'An error occurred: {str(e)}', 'danger')
      print(f"\n\n\nError sending email: {e}", file=sys.stderr) ###

    return redirect(url_for('main.contact'))
  
  flash_messages = get_flashed_messages()

  print(f"\n\n\nForm not submitted or validation failed", file=sys.stderr) ###

  return render_template("contact.html", title="Contact With Us", form= form,
                         flash_messages= flash_messages)


@main.route("/faq")
def faq():
  return render_template("faq.html", title="FAQ")

'''
#pass stuff to navbar
@main.context_processor
def app():
  form =SearchForm()
  return dict(form = form)

'''



@main.route("/search", methods=['POST', 'GET'])
def search():
  form =SearchForm()
  query= None
  page=request.args.get('page', 1, type=int) 


  if form.validate_on_submit():
    query= form.query.data
    session['query'] = query

  query = session.get('query')

  if query:
    courses=Course.query.filter(Course.title.like('%'+ query +'%') )
    paginated_courses = courses.paginate(page= page, per_page= 6)
  else:
    paginated_courses = None

  return render_template("search.html",
                            title="Search Results",
                            form=form,
                            query=query,
                            paginated_courses= paginated_courses
                            )
  
  

website/users/routes.py
from website.models import User, Course, Category, JoinedCourse
from flask import render_template, url_for, flash, redirect, request
from website.users.forms import RegistrationForm, LoginForm, UpdateProfileForm
from website.users.forms import RequestResetPasswordForm, ResetPasswordForm
from website import bcrypt, db
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user,
    login_required,
)
from flask import get_flashed_messages

###methods###
from website.helper import lessonCountInCourse, save_picture
from website.users.helper import send_reset_email


from flask import Blueprint
users_bp=Blueprint('users_bp',__name__)


@users_bp.route("/register", methods=["POST","GET"])
def register():
  if current_user.is_authenticated:
    return redirect(url_for("main.home"))
  #decode("utf-8") to convert password into string
  form=RegistrationForm()

  if form.validate_on_submit():
    hashed_password=bcrypt.generate_password_hash(form.password.data).decode("utf-8")
    user=User(fname=form.fname.data, lname=form.lname.data, email=form.email.data,
              password=hashed_password, is_instructor=False, is_admin=False)
    db.session.add(user)
    db.session.commit()
    flash(message="Account created successfully",category="success")
    return redirect( url_for("users_bp.login") )
  
  flash_messages = get_flashed_messages()
  return render_template("register.html",
                         title="Register", 
                         form=form,
                         flash_messages= flash_messages
                         )


@users_bp.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
       
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.home'))

        else:
            flash("Invalid email or password", "error")
            # Pass the form back to the template with errors
            flash_messages = get_flashed_messages() 
            return render_template("login.html", title="Login", form=form,flash_messages= flash_messages)
             
    
    flash_messages = get_flashed_messages() 
    return render_template("login.html", title="Login",
                           form= form, flash_messages= flash_messages)


@users_bp.route("/logout")
def logout():
  logout_user()
  return redirect(url_for("main.home"))



@users_bp.route("/dashboard",methods=["GET", "POST"]) #GET for review POST for update
@login_required
def dashboard():
  default_category=Category.query.first()
  flash_messages = get_flashed_messages()
  return render_template("dashboard.html",
                          title="dashboard",
                          default_category=default_category.title,
                          flash_messages=flash_messages,
                           active_tab="profile")



@users_bp.route("/dashboard/profile", methods=["GET","POST"])
@login_required
def profile(): 
  profile_form=UpdateProfileForm()
  if profile_form.validate_on_submit():
     
     if profile_form.picture.data:
        picture_file=save_picture(profile_form.picture.data,
                                  path="static/images/user_pics",
                                  output_size=(200,200) 
                                )
        current_user.img_file=picture_file


     if profile_form.email.data is not None:  # Check if email data is not None
        current_user.email = profile_form.email.data
      
     current_user.bio=profile_form.bio.data
     db.session.commit()
     flash("your Profile has currently Updated",category="success")
     return redirect(url_for("users_bp.profile"))
  
  elif request.method == 'GET':
    profile_form.bio.data=current_user.bio
    profile_form.email.data=current_user.email

  img_file = url_for("static", filename=f"images/user_pics/{current_user.img_file}")

  flash_messages = get_flashed_messages()

  return render_template("profile.html",
                          title="Profile",
                          profile_form=profile_form,
                          img_file=img_file, active_tab="profile",
                          flash_messages=flash_messages
                        )


@users_bp.route("/enroll_user/<string:course_title>", methods=['GET', 'POST'])
@login_required
def enroll_user(course_title):
  
  course = Course.query.filter_by(title=course_title).first_or_404()
  new_enrollment = JoinedCourse(user_id=current_user.id,course_id=course.id)
  db.session.add(new_enrollment)
  db.session.commit()

  flash_messages = get_flashed_messages()
  
  return render_template(
    "enroll_done.html",
    title="Enroll done",
    flash_messages=flash_messages
    )


@users_bp.route("/my_learning", methods=['GET'])
@login_required
def my_learning():
  my_courses = db.session.query(Course).join(JoinedCourse).filter(JoinedCourse.user_id == current_user.id).all()
  flash_messages = get_flashed_messages()
  return render_template(
        "my_learning.html",
        title="My Learning",
          my_courses = my_courses,
        flash_messages=flash_messages
    )


@users_bp.route("/author_info/<int:author_id>", methods=['GET'])
def author_info(author_id):
  author=User.query.filter_by(id=author_id).first_or_404()
  courses=Course.query.filter_by(author= author).all() #lessonCountInCourse()
  lessons_count={}
  for course in courses:
     lessons_count[course.id]= lessonCountInCourse(course.id)
  return render_template("author.html",
                          courses= courses,
                          author= author,
                          lessons_count= lessons_count
                        ) 


@users_bp.route("/reset_password", methods=['GET','POST'])
def reset_request():
   if current_user.is_authenticated:
      return redirect(url_for('main.home'))
   form = RequestResetPasswordForm()
   if form.validate_on_submit():
      user=User.query.filter_by(email= form.email.data).first()
      if user:
         send_reset_email(user)
         flash('If this account exist, you will recieve an email with isntruction', 'info')
         return redirect(url_for('users_bp.login'))
   return render_template('reset_request.html', title= 'Reset Password' ,form= form)


@users_bp.route("/reset_password/<token>", methods=['GET','POST'])
def reset_password(token):
   if current_user.is_authenticated:
      return redirect(url_for('main.home'))
   
   user= User.verify_reset_token(token)
   if not user:
      flash('The token is invalid or expired', 'warning')
      return redirect(url_for('users_bp.reset_request'))
   
   form= ResetPasswordForm()
   if form.validate_on_submit():
      hashed_password=bcrypt.generate_password_hash(form.password.data).decode("utf-8")
      user.password= hashed_password
      db.session.commit()
    
      flash(message="your Password has been updated successfully",category="success")
      return redirect( url_for("users_bp.login") )    
      
   return render_template('reset_password.html', title='Reset Password', form = form)

website/templates/category.html
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

	<!--main style-->
	<link rel="stylesheet" type="text/css" href="../static/styles/form.css">
</head>


{% extends "layout.html" %}

{% block content %}



<!-- PAGE TITLE
    ================================================== -->
<header class="py-8 py-md-11" style="background-image: none;">
	<div class="container text-center py-xl-2">
		<h1 class="display-4 fw-semi-bold mb-0">{{ category.title }}</h1>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb breadcrumb-scroll justify-content-center">
				<li class="breadcrumb-item">
					<a class="text-gray-800" href="#">
						Home
					</a>
				</li>
				<li class="breadcrumb-item text-gray-800 active" aria-current="page">
					{{ category.title }}
				</li>
			</ol>
		</nav>
	</div>
	<!-- Img -->
	<img class="d-none img-fluid" src="...html" alt="...">
</header>


<!-- CONTROL BAR
  ================================================== -->
<div class="container mb-6 mb-xl-8 z-index-2">
	<div class="d-xl-flex align-items-center">
		<p class="mb-xl-0">We found <span class="text-dark">{{ courses_count }} courses</span> available for you</p>

		<!--Categories-->
		<div class="mb-4 mb-xl-0 ms-xl-6">
			<select id="categorySelect" class="form-select form-select-sm text-dark shadow-none dropdown-menu-end">
				{% for ctg in categories %}
				<option value="{{ url_for('categories_bp.category_list', category_title=ctg.title) }}" {% if ctg.title==category.title %}
					selected {% endif %}>
					{{ ctg.title }}
				</option>
				{% endfor %}
			</select>
		</div>

		<script>
			document.getElementById('categorySelect').addEventListener('change', function () {
				var selectedOption = this.value;
				if (selectedOption) {
					window.location.href = selectedOption;
				}
			});
		</script>

	</div>
</div>

<!-- COURSE LIST V1
  ================================================== -->
<div class="container pb-4 pb-xl-7">
	<div class="row row-cols-md-2 row-cols-xl-3 mb-6 mb-xl-3">

		{% for course in category_courses %}
		<div class="col-md pb-4 pb-md-7">
			<!-- Card -->
			<div class="card border shadow p-2 lift sk-fade">
				<!-- Image -->
				<div class="card-zoom position-relative">
					<a href="{{ url_for('courses_bp.course', course_title=course.title) }}" class="card-img sk-thumbnail d-block">
						<img class="rounded shadow-light-lg" src="../static/images/course_pics/{{ course.icon }}" alt="...">
					</a>

					<span class="badge sk-fade-bottom badge-lg badge-orange badge-pill badge-float bottom-0 left-0 mb-4 ms-4">
						<span class="text-white text-uppercase fw-bold font-size-xs">BEST SELLER</span>
					</span>
				</div>

				<!-- Footer -->
				<div class="card-footer px-2 pb-2 mb-1 pt-4 position-relative">


					<!-- Instructor image -->
					<a href="instructors-single.html" class="d-block">
						<div
							class="avatar sk-fade-right avatar-xl badge-float position-absolute top-0 right-0 mt-n6 me-5 rounded-circle shadow border border-white border-w-lg">
							<img src="{{ url_for('static', filename='images/user_pics/'+course.author.img_file) }} " alt="..."
								class="avatar-img rounded-circle">
						</div>
					</a>

					<!-- Category -->
					<a href="course-single-v3.html">
						<span class="mb-1 d-inline-block text-gray-800">
							{{course.category.title}}
						</span>
					</a>


					<!-- Course name -->
					<div class="position-relative">
						<a href="course-single-v3.html" class="d-block stretched-link">
							<h4 class="line-clamp-2 h-md-48 h-lg-58 me-md-6 me-lg-10 me-xl-4 mb-2">
								{{course.title}}
							</h4>
						</a>



						<div class="row mx-n2 align-items-end">
							<div class="col px-2">
								<ul class="nav mx-n3">
									<li class="nav-item px-3">
										<div class="d-flex align-items-center">
											<div class="me-2 d-flex icon-uxs text-secondary">
												<!-- Icon -->
												<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
													<path
														d="M17.1947 7.06802L14.6315 7.9985C14.2476 7.31186 13.712 6.71921 13.0544 6.25992C12.8525 6.11877 12.6421 5.99365 12.4252 5.88303C13.0586 5.25955 13.452 4.39255 13.452 3.43521C13.452 1.54098 11.9124 -1.90735e-06 10.0197 -1.90735e-06C8.12714 -1.90735e-06 6.58738 1.54098 6.58738 3.43521C6.58738 4.39255 6.98075 5.25955 7.61414 5.88303C7.39731 5.99365 7.1869 6.11877 6.98502 6.25992C6.32752 6.71921 5.79178 7.31186 5.40787 7.9985L2.8447 7.06802C2.33612 6.88339 1.79688 7.26044 1.79688 7.80243V16.5178C1.79688 16.8465 2.00256 17.14 2.31155 17.2522L9.75312 19.9536C9.93073 20.018 10.1227 20.0128 10.2863 19.9536L17.7278 17.2522C18.0368 17.14 18.2425 16.8465 18.2425 16.5178V7.80243C18.2425 7.26135 17.704 6.88309 17.1947 7.06802ZM10.0197 1.5625C11.0507 1.5625 11.8895 2.40265 11.8895 3.43521C11.8895 4.46777 11.0507 5.30792 10.0197 5.30792C8.98866 5.30792 8.14988 4.46777 8.14988 3.43521C8.14988 2.40265 8.98866 1.5625 10.0197 1.5625ZM9.23844 18.1044L3.35938 15.9703V8.91724L9.23844 11.0513V18.1044ZM10.0197 9.67255L6.90644 8.54248C7.58164 7.51892 8.75184 6.87042 10.0197 6.87042C11.2875 6.87042 12.4577 7.51892 13.1329 8.54248L10.0197 9.67255ZM16.68 15.9703L10.8009 18.1044V11.0513L16.68 8.91724V15.9703Z"
														fill="currentColor" />
												</svg>

											</div>
											<!-- lessons number -->
											<div class="font-size-sm">5 lessons</div>
										</div>
									</li>
									<li class="nav-item px-3">
										<div class="d-flex align-items-center">
											<div class="me-2 d-flex icon-uxs text-secondary">
												<!-- Icon -->
												<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
													<path
														d="M14.3164 4.20996C13.985 4.37028 13.8464 4.76904 14.0067 5.10026C14.4447 6.00505 14.6667 6.98031 14.6667 8C14.6667 11.6759 11.6759 14.6667 8 14.6667C4.32406 14.6667 1.33333 11.6759 1.33333 8C1.33333 4.32406 4.32406 1.33333 8 1.33333C9.52328 1.33333 10.9543 1.83073 12.1387 2.77165C12.4259 3.00098 12.846 2.95296 13.0754 2.66471C13.3047 2.37663 13.2567 1.95703 12.9683 1.72803C11.5661 0.613607 9.8016 0 8 0C3.58903 0 0 3.58903 0 8C0 12.411 3.58903 16 8 16C12.411 16 16 12.411 16 8C16 6.77767 15.7331 5.60628 15.2067 4.51969C15.0467 4.18766 14.6466 4.04932 14.3164 4.20996Z"
														fill="currentColor" />
													<path
														d="M7.99967 2.66663C7.63167 2.66663 7.33301 2.96529 7.33301 3.33329V7.99996C7.33301 8.36796 7.63167 8.66663 7.99967 8.66663H11.333C11.701 8.66663 11.9997 8.36796 11.9997 7.99996C11.9997 7.63196 11.701 7.33329 11.333 7.33329H8.66634V3.33329C8.66634 2.96529 8.36768 2.66663 7.99967 2.66663Z"
														fill="currentColor" />
												</svg>

											</div>
											<!-- Course duration -->
											<div class="font-size-sm">8h 12m</div>
										</div>
									</li>
								</ul>
							</div>

							<div class="col-auto px-2 text-right">

								<ins class="h4 mb-0 d-block mb-lg-n1">{{course.price}} JD</ins>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		{%endfor%}

	</div>






	<div class="text-center">
		<a class="btn btn-outline-white mw-300p d-flex mx-auto read-more" data-bs-toggle="collapse"
			href="#loadcollapseExample" role="button" aria-expanded="false" aria-controls="loadcollapseExample">
			<span class="d-inline-flex mx-auto align-items-center more">
				<!-- Icon -->
				<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
					<path
						d="M5.76026 17.0396C5.16013 17.0396 4.65015 17.2495 4.23011 17.6695C3.81023 18.0899 3.60014 18.5998 3.60014 19.1999C3.60014 19.8001 3.81008 20.31 4.23011 20.7303C4.65031 21.1503 5.16029 21.3603 5.76026 21.3603C6.35031 21.3603 6.85772 21.1503 7.2828 20.7303C7.70772 20.3105 7.92018 19.8001 7.92018 19.1999C7.92018 18.5998 7.70777 18.0902 7.2828 17.6695C6.85766 17.2499 6.35031 17.0396 5.76026 17.0396Z"
						fill="currentColor" />
					<path
						d="M5.28028 12.4799C5.28028 11.8199 5.04538 11.2551 4.57533 10.7847C4.10533 10.3147 3.54024 10.0797 2.88026 10.0797C2.22023 10.0797 1.65524 10.3147 1.18519 10.7847C0.715245 11.2547 0.480297 11.8197 0.480297 12.4799C0.480297 13.1398 0.715192 13.7045 1.18519 14.1746C1.65524 14.6448 2.22023 14.8798 2.88026 14.8798C3.54024 14.8798 4.10533 14.6448 4.57533 14.1746C5.04538 13.7048 5.28028 13.1398 5.28028 12.4799Z"
						fill="currentColor" />
					<path
						d="M19.2 6.96016C19.5297 6.96016 19.8127 6.84247 20.0474 6.60758C20.2824 6.37248 20.4001 6.08988 20.4001 5.75994C20.4001 5.42985 20.2824 5.14746 20.0474 4.91251C19.8126 4.67741 19.5297 4.55994 19.2 4.55994C18.8699 4.55994 18.5873 4.67762 18.3523 4.91251C18.1174 5.14751 17.9999 5.42985 17.9999 5.75994C17.9999 6.09003 18.1174 6.37248 18.3523 6.60758C18.5873 6.84268 18.8699 6.96016 19.2 6.96016Z"
						fill="currentColor" />
					<path
						d="M5.76041 3.12012C5.0303 3.12012 4.40784 3.37766 3.89281 3.89258C3.37773 4.4075 3.12035 5.03001 3.12035 5.75997C3.12035 6.49019 3.37773 7.11244 3.89281 7.62757C4.40799 8.14265 5.03046 8.40013 5.76041 8.40013C6.49037 8.40013 7.11288 8.14249 7.6278 7.62757C8.14272 7.11244 8.40026 6.49003 8.40026 5.75997C8.40026 5.03001 8.14272 4.4075 7.6278 3.89258C7.11288 3.37766 6.49037 3.12012 5.76041 3.12012Z"
						fill="currentColor" />
					<path
						d="M23.0999 11.4597C22.82 11.1796 22.48 11.0398 22.0801 11.0398C21.6799 11.0398 21.3399 11.1796 21.06 11.4597C20.7802 11.7397 20.6404 12.0798 20.6404 12.48C20.6404 12.8798 20.7802 13.2204 21.06 13.4998C21.3401 13.7799 21.6799 13.9197 22.0801 13.9197C22.48 13.9197 22.8202 13.7799 23.0999 13.4998C23.38 13.22 23.5197 12.8798 23.5197 12.48C23.5197 12.08 23.3802 11.7399 23.0999 11.4597Z"
						fill="currentColor" />
					<path
						d="M19.2 17.5198C18.7397 17.5198 18.3448 17.6846 18.0147 18.0147C17.6849 18.3445 17.5199 18.7396 17.5199 19.1999C17.5199 19.6598 17.6849 20.055 18.0147 20.3852C18.3448 20.7152 18.7398 20.8799 19.2 20.8799C19.6599 20.8799 20.0549 20.7149 20.385 20.3852C20.7151 20.0551 20.88 19.66 20.88 19.1999C20.88 18.7396 20.7151 18.3449 20.385 18.0147C20.055 17.6846 19.6599 17.5198 19.2 17.5198Z"
						fill="currentColor" />
					<path
						d="M12.4801 20.1595C11.9501 20.1595 11.4976 20.3474 11.1223 20.7225C10.7475 21.0975 10.5599 21.5498 10.5599 22.0799C10.5599 22.6099 10.7473 23.0623 11.1223 23.4373C11.4976 23.8124 11.9499 24.0001 12.4801 24.0001C13.0102 24.0001 13.4625 23.8124 13.8376 23.4373C14.2126 23.0623 14.4001 22.6099 14.4001 22.0799C14.4001 21.5498 14.2126 21.0975 13.8376 20.7225C13.4625 20.3474 13.0102 20.1595 12.4801 20.1595Z"
						fill="currentColor" />
					<path
						d="M12.4801 0C11.6802 0 10.9999 0.279867 10.4399 0.839864C9.87998 1.39991 9.60001 2.08006 9.60001 2.88C9.60001 3.67999 9.87988 4.35982 10.4399 4.91992C10.9999 5.47981 11.6801 5.75984 12.4801 5.75984C13.2804 5.75984 13.9602 5.47997 14.52 4.91992C15.0799 4.36008 15.3598 3.67999 15.3598 2.88C15.3598 2.08012 15.0799 1.40012 14.52 0.839864C13.9602 0.280025 13.2804 0 12.4801 0Z"
						fill="currentColor" />
				</svg>

				<span class="ms-2">LOAD MORE</span>
			</span>

			<span class="less mx-auto">
				LOAD LESS
			</span>
		</a>
	</div>
</div>






{%endblock content %}

website/templates/coming-soon.html
<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

  <!--main style-->
  <link rel="stylesheet" type="text/css" href="../static/styles/form.css">
</head>



{% extends "layout.html" %}

{% block content %}

 <!-- coming soon
    ================================================== -->
    <div class="container my-10">
     
      <div class="row">
          <div class="col-xl-6 mx-auto text-center">
              <h1 class="display-6">We will Coming Soon!</h1>
             


              <a href="{{url_for('main.home')}}" class="d-inline-block text-underline text-blue">Back to home</a>
          </div>
      </div>
  </div>


{% endblock content %}

website/templates/update_unit.html
<head>

	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

 <!-- Main Style -->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/form.css') }}">


</head>


{% extends "layout.html" %}


{%block content%}

<div class="container my-5">

	<form action="" method="POST" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			
			<legend class="border-bottom my-3">Update Unit</legend>
			
			
			<div class="mb-3">
				{{ form.title.label(class='form-control-label') }}
				{% if form.title.errors %}
				{{ form.title(class='form-control is-invalid') }}
				<div class="invalid-feedback">
	
					{% for error in form.title.errors %}
					<span class="error">{{error}}</span>
					{% endfor %}
	
				</div>
				{% else %}
				{{ form.title(class='form-control') }}
	
				{% endif %}
			</div>
	
			<div class="form-group">
				<div class="col-12">
					<button class="btn-submit" type="submit">Update</button>
				</div>
			</div>
	
	</form>
	
</div>

{%endblock content%}